# Generated by Django 4.2.7 on 2023-11-28 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_relations', '0001_initial'),
        ('accounts', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(related_name='following_users', through='user_relations.Relations', to=settings.AUTH_USER_MODEL),
        ),
    ]
