# Generated by Django 4.2.7 on 2023-11-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_favorites_post_favorites_by'),
        ('accounts', '0006_customuser_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites_user',
            field=models.ManyToManyField(related_name='favorited_by', to='post.post'),
        ),
    ]
