# Generated by Django 4.2.7 on 2023-11-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_favorites_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='favorites_user',
            new_name='favorites_post',
        ),
    ]
