# Generated by Django 4.2.7 on 2023-12-12 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_relations', '0002_remove_relations_follower_remove_relations_following_and_more'),
        ('accounts', '0008_rename_favorites_user_customuser_favorites_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(related_name='follower_users', through='user_relations.Relations', to=settings.AUTH_USER_MODEL),
        ),
    ]
