# Generated by Django 4.2.7 on 2023-12-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='pictures/default_profile_picture/profile_picture.png', null=True, upload_to='profile_images/'),
        ),
    ]
