# Generated by Django 4.2.7 on 2023-11-28 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ManyToManyField(related_name='following_relations', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(related_name='followers_relations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
