# Generated by Django 4.2.7 on 2023-12-13 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_relations', '0002_remove_relations_follower_remove_relations_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relations',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relations',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to=settings.AUTH_USER_MODEL),
        ),
    ]
