# Generated by Django 4.2.7 on 2023-11-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_favorites_post_favorites_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='favorites_by',
            new_name='favorites_user',
        ),
    ]
