# Generated by Django 4.2.7 on 2023-11-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
        ('post', '0003_rename_favorites_by_post_favorites_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(related_name='post', to='hashtags.hashtag'),
        ),
    ]
